daktary:
  home: /infolab-cd33/datalunch
  meta:
    title: "Fiches ressources issues des datalunch"
    description: "Dans le cadre de l'infolab interne du département de la Gironde, des fiches méthodologiques et présentation de thématiques ont été réalisées."

  ghRepos:
  - label: Datalunch
    account: infolab-cd33
    repo: datalunch
    folder: /

  - label: multibao
    account: multibao
    repo: contributions
    folder: contributions

  dkCss: assets/css/datalunch.css
  dkImgPath: assets/img
  dk404: https://raw.githubusercontent.com/daktary/contribs/master/assets/img/error404.png
  
prose:
  rooturl: 'examples'
  media: 'media'
  metadata:
    contributions:
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: "author"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Manip"
              value: "manip"
            - name: "Geo"
              value: "geo"
            - name: "Dataviz"
              value: "dataviz"
            - name: "Agile"
              value: "agile"
            - name: "Collaboratif"
              value: "collaboratif"
            - name: "Scopyleft"
              value: "scopyleft"
            - name: "Meteor"
              value: "meteor"
            - name: "Lean"
              value: "lean"

